import { PDFDocument, StandardFonts, rgb } from "pdf-lib"
import type { LeaseFormData } from "./types"

// Generic fallback lease agreement, generated from scratch (no official template).
// Used for provinces we haven't mapped an official form for yet. Clearly labeled
// as a general agreement, not a province-mandated form.

const NAVY = rgb(0.11, 0.22, 0.42)
const GREY = rgb(0.4, 0.4, 0.4)
const BLACK = rgb(0.1, 0.1, 0.1)

function fmtMoney(v: number | string | undefined): string {
  if (v === undefined || v === null || v === "") return "—"
  const n = typeof v === "number" ? v : parseFloat(v)
  if (Number.isNaN(n)) return String(v)
  return `$${n.toLocaleString("en-CA", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`
}

function fmtDate(d?: string): string {
  if (!d) return "—"
  try {
    return new Date(d + "T00:00:00").toLocaleDateString("en-CA", {
      year: "numeric",
      month: "long",
      day: "numeric",
    })
  } catch {
    return d
  }
}

function name(p?: { first: string; last: string }): string {
  if (!p) return "—"
  return [p.first, p.last].filter(Boolean).join(" ") || "—"
}

function addr(a?: LeaseFormData["rental_unit"]): string {
  if (!a) return "—"
  const line = [a.unit ? `Unit ${a.unit}` : "", a.street, a.city, a.province, a.postal]
    .filter(Boolean)
    .join(", ")
  return line || "—"
}

export async function generateGenericLease(
  data: LeaseFormData,
  provinceName: string,
): Promise<Uint8Array> {
  const doc = await PDFDocument.create()
  const font = await doc.embedFont(StandardFonts.Helvetica)
  const bold = await doc.embedFont(StandardFonts.HelveticaBold)

  let page = doc.addPage([612, 792]) // Letter
  const margin = 56
  let y = 792 - margin
  const width = 612 - margin * 2

  const line = (text: string, opts: { size?: number; f?: typeof font; color?: typeof BLACK; gap?: number } = {}) => {
    const size = opts.size ?? 11
    const f = opts.f ?? font
    if (y < margin + 40) {
      page = doc.addPage([612, 792])
      y = 792 - margin
    }
    page.drawText(text, { x: margin, y, size, font: f, color: opts.color ?? BLACK })
    y -= (opts.gap ?? size + 6)
  }

  const field = (label: string, value: string) => {
    if (y < margin + 40) {
      page = doc.addPage([612, 792])
      y = 792 - margin
    }
    page.drawText(label, { x: margin, y, size: 9, font: bold, color: GREY })
    page.drawText(value, { x: margin + 160, y, size: 11, font, color: BLACK })
    y -= 20
  }

  // Header
  line("Residential Tenancy Agreement", { size: 20, f: bold, color: NAVY, gap: 26 })
  line(`${provinceName} · Generated by HomeSuite Manager`, { size: 10, color: GREY, gap: 22 })

  // Parties
  line("Parties", { size: 13, f: bold, color: NAVY, gap: 20 })
  field("Landlord", name(data.landlords[0]))
  if (data.landlords[1]) field("Landlord (2)", name(data.landlords[1]))
  field("Tenant", name(data.tenants[0]))
  if (data.tenants[1]) field("Tenant (2)", name(data.tenants[1]))
  if (data.landlord_email) field("Landlord email", data.landlord_email)
  if (data.tenant_email) field("Tenant email", data.tenant_email)
  y -= 8

  // Property
  line("Rental Unit", { size: 13, f: bold, color: NAVY, gap: 20 })
  field("Address", addr(data.rental_unit))
  y -= 8

  // Term
  line("Term", { size: 13, f: bold, color: NAVY, gap: 20 })
  field("Type", data.tenancy_type === "periodic" ? `Periodic (${data.periodic_type ?? "monthly"})` : "Fixed term")
  field("Start date", fmtDate(data.start_date))
  if (data.tenancy_type === "fixed") {
    field("End date", fmtDate(data.end_date))
    field(
      "At end of term",
      data.end_of_term_action === "vacate" ? "Tenant must vacate" : "Continues month-to-month",
    )
  }
  y -= 8

  // Rent
  line("Rent & Deposits", { size: 13, f: bold, color: NAVY, gap: 20 })
  field("Monthly rent", fmtMoney(data.monthly_rent))
  field("Due day", data.rent_due_day ? `Day ${data.rent_due_day} of each month` : "—")
  if (data.rent_includes && data.rent_includes.length > 0) {
    field("Rent includes", data.rent_includes.join(", "))
  }
  field("Security deposit", fmtMoney(data.security_deposit))
  if (data.pet_deposit) field("Pet deposit", fmtMoney(data.pet_deposit))
  y -= 8

  // Additional terms
  if (data.additional_terms) {
    line("Additional Terms", { size: 13, f: bold, color: NAVY, gap: 20 })
    // naive wrap
    const words = data.additional_terms.split(/\s+/)
    let cur = ""
    for (const w of words) {
      if ((cur + " " + w).length > 90) {
        line(cur, { size: 10 })
        cur = w
      } else {
        cur = cur ? cur + " " + w : w
      }
    }
    if (cur) line(cur, { size: 10 })
    y -= 8
  }

  // Signatures
  if (y < margin + 120) {
    page = doc.addPage([612, 792])
    y = 792 - margin
  }
  y -= 10
  line("Signatures", { size: 13, f: bold, color: NAVY, gap: 28 })
  const sigLine = (label: string) => {
    page.drawLine({
      start: { x: margin, y: y + 2 },
      end: { x: margin + 240, y: y + 2 },
      thickness: 0.75,
      color: GREY,
    })
    page.drawLine({
      start: { x: margin + 300, y: y + 2 },
      end: { x: margin + width, y: y + 2 },
      thickness: 0.75,
      color: GREY,
    })
    page.drawText(`${label} signature`, { x: margin, y: y - 12, size: 8, font, color: GREY })
    page.drawText("Date", { x: margin + 300, y: y - 12, size: 8, font, color: GREY })
    y -= 46
  }
  sigLine("Landlord")
  sigLine("Tenant")

  // Honesty footer
  y = margin - 6
  page.drawText(
    "This is a general tenancy agreement generated by HomeSuite Manager. It is not a government-",
    { x: margin, y: y + 8, size: 7.5, font, color: GREY },
  )
  page.drawText(
    `mandated form. Confirm it meets ${provinceName}'s residential tenancy requirements before use.`,
    { x: margin, y, size: 7.5, font, color: GREY },
  )

  return await doc.save()
}
